pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "python:3.10"
        GIT_CREDENTIALS = 'exam' // credentials for git
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Make sure we're checking out the correct branch
                    checkout scm
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Install dependencies (e.g., flake8, bandit)
                    sh '''
                        pip install --upgrade pip
                        pip install flake8 bandit
                    '''
                }
            }
        }

        stage('Lint & Security Scan') {
            steps {
                script {
                    // Run linting and security scan
                    sh '''
                        flake8 .
                        bandit -r .
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    sh '''
                        docker build -t my-image .
                    '''
                }
            }
        }

        stage('Run Tests in Container') {
            steps {
                script {
                    // Run tests inside the container
                    sh '''
                        docker run --rm my-image pytest
                    '''
                }
            }
        }

        stage('Integration Test with Docker Compose') {
            steps {
                script {
                    // Use Docker Compose for integration testing
                    sh '''
                        docker-compose -f docker-compose.yml up --build
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    // Push Docker image to Docker Hub
                    sh '''
                        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                        docker push my-image
                    '''
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    // Clean up any resources or containers
                    sh '''
                        docker system prune -f
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
