// pipeline {
//     agent {
//         docker {
//             image 'python:3.10'
//         }
//     }
//     parameters {
//         choice(name: 'REPO_NAME', choices: ['be', 'fe'], description: 'Select the repository to build')
//     }
//     environment {
//         DOCKERHUB_CREDENTIALS = credentials('exam')
//         DOCKER_REGISTRY = 'tzachaker'
//         IMAGE_TAG = "${env.BUILD_NUMBER}"
//     // 
//     stages {
//         stage('Clone Repository') {
//             steps {
//                 git branch: 'workshop/argo-jenkins-exam/exam-code/docker', 
//                     url: 'https://github.com/tzachaker/devopshift-welcome.git'
//             }
//         }
        
//         stage('Lint & Security Scan') {
//             steps {
//                 sh 'pip install flake8 bandit'
//                 sh 'flake8 ${REPO_NAME}/'
//                 sh 'bandit -r ${REPO_NAME}/'
//             }
//         }
        
//         stage('Install Dependencies') {
//             steps {
//                 sh 'pip install -r ${REPO_NAME}/requirements.txt'
//             }
//         }
        
//         stage('Build Docker Image') {
//             steps {
//                 sh "docker build -t $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG $REPO_NAME/"
//                 sh "docker tag $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG $DOCKER_REGISTRY/$REPO_NAME:latest"
//             }
//         }
        
//         stage('Run Tests in Container') {
//             steps {
//                 sh "docker run --rm $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG pytest ${REPO_NAME}/tests/"
//             }
//         }
        
//         stage('Integration Test with Docker Compose') {
//             steps {
//                 sh 'docker-compose up -d'
//                 sleep time: 10, unit: 'SECONDS'  // זמן להעלאת המכולות
//                 sh "curl -f http://localhost:5000 || exit 1"  // שנה את הפורט ל-5002 אם זה ה-BE
//                 sh 'docker-compose down'
//             }
//         }
        
//         stage('Push to Docker Hub') {
//             steps {
//                 sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
//                 sh "docker push $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG"
//                 sh "docker push $DOCKER_REGISTRY/$REPO_NAME:latest"
//             }
//         }

//         stage('Cleanup') {
//             steps {
//                 sh 'docker system prune -af'
//             }
//         }
//     }
// }
